# spring security
security:
  basic:
    enabled: true

# spring cloud config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LyneLiu/spring_cloud_simple/
          search-paths: spring-cloud-config
        svn:
          uri:
          search-paths:
      enabled: false